language: go
sudo: false
dist: focal

branches:
  only:
    - master
    - development
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

services:
  - docker

go:
  - 1.15.x

matrix:
  fast_finish: true

before_install:
  - sudo apt-get update
  - docker pull minio/minio
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
  - nvm install 12.18.3

install:
  - sudo apt-get -y install youtube-dl ffmpeg
  - npm install -g snyk
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; else go get -t -v ./...; fi

script:
  - docker run -d -p 127.0.0.1:9000:9000 -e "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE" -e "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" minio/minio server /data
  - snyk test
  - golangci-lint run
  - go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
  - curl -sfL https://git.io/goreleaser | sh -s -- check

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
